spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

spring.application.name=additional-service
external.api.base-url=http://spring-boot-app:8080
main.service.url=${external.api.base-url}

service.statistic.delay=${STATISTIC_DELAY:30000}
statistics.observability=${ENABLE_OBSERVABILITY_STATISTICS:true}
observability.intervals=${OBSERVABILITY_INTERVALS:10,30,60}
service.statistic.observability.delay=${STATISTIC_DELAY:30000}
